name: 'Get & cache dependencies'
description: 'Get the dependencies via npm and cache them.'
inputs:
    caching:
      description: 'whether to cache or not'
      required: false
      default: 'true'
outputs:
    used-cache:
      description: 'whether the cache  was  used.'
      value: ${{steps.install}}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies == 'true'
      if: inputs.caching
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' && inputs.caching != 'true'
      id: install
      run: |
        npm ci
        echo "::set-output name=cache::'${{inputs.caching}}'"
      shell: bash
